select year(A.DIFFERENTIATION_DATE) as 'YEAR', B.MAX_SIZE - A.SIZE_OF_COLONY as 'YEAR_DEV', A.ID
from ECOLI_DATA A, (
    select year(DIFFERENTIATION_DATE) as 'YEAR', max(SIZE_OF_COLONY) as 'MAX_SIZE'
    from ECOLI_DATA
    group by year(DIFFERENTIATION_DATE)
) B
where year(A.DIFFERENTIATION_DATE) = B.YEAR
order by YEAR, YEAR_DEV;